# Generated by Django 5.0.4 on 2024-04-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetAdoption', '0002_shelter_alter_pet_id_pet_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
