# Generated by Django 5.0.4 on 2024-04-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetAdoption', '0003_shelter_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
