# Generated by Django 5.0.4 on 2024-04-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetAdoption', '0004_rename_phone_number_shelter_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
