# Generated by Django 5.0.4 on 2024-05-26 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PetAdoption', '0001_initial'),
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_children', models.IntegerField(default=0)),
                ('number_of_pets', models.IntegerField(default=0)),
                ('residence_type', models.CharField(max_length=100)),
                ('income_range', models.CharField(max_length=100)),
                ('activity_level', models.CharField(max_length=100)),
                ('time_availability', models.CharField(max_length=100)),
                ('prior_pet_experience', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Registration.generaluser')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='PetAdoption.pet')),
            ],
        ),
    ]
